name: 'Bump Version'
on:
  push:
    branches: [main]
    paths: ['src/**']
    tags: ['v*']
  schedule:
    - cron: '0 0 * * MON'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Check diff and update version'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ./scripts/bump_version.sh "${{ vars.GH_ACTIONS_USERNAME }}" "$BRANCH_NAME"