name: 'Bump Version'
on:
  push:
    branches: ['main']
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  workflow_dispatch:

jobs:
  bump-version:
    name: 'Bump Version'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install Dependencies'
        run: yarn global add semver
      - name: 'Run Version Bump'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTIONS_USERNAME: ${{ vars.GH_ACTIONS_USERNAME }}
        run: make bump-version