name: 'Checksums'
on:
    workflow_dispatch:
    release:
        types:
            - created

jobs:
    checksums:
        name: 'Checksums'
        if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            packages: write
        env:
            ARCH_UTIL_SCRIPT_PATH: './scripts/archlinux_util.sh'
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}

            - name: Generate and sign checksum
              run: |
                  echo "🚀 Generating checksums..."
                  cd $(dirname ${{ env.ARCH_UTIL_SCRIPT_PATH }})
                  sha256sum $(basename ${{ env.ARCH_UTIL_SCRIPT_PATH }}) > $(basename ${{ env.ARCH_UTIL_SCRIPT_PATH }}).sha256
                  gpg --detach-sign --armor $(basename ${{ env.ARCH_UTIL_SCRIPT_PATH }}).sha256
                  echo "✅ Checksums generated."

            - name: Get release
              id: get_release
              shell: bash
              run: |
                  echo "🚀 Getting release..."
                  echo "result=$(git describe --tags --abbrev=0 --match 'v[0-9]*.[0-9]*.[0-9]*')" >> $GITHUB_OUTPUT
                  echo "✅ Release retrieved."

            - name: Upload checksum
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LATEST_TAG: ${{ steps.get_release.outputs.result }}
              run: |
                  echo "🚀 Uploading checksums..."
                  cd $(dirname ${{ env.ARCH_UTIL_SCRIPT_PATH }})
                  for file in $(ls *.sha256 *.sha256.asc); do
                      gh release upload ${{ env.LATEST_TAG }} $file
                  done
                  echo "✅ Checksums uploaded."
