name: 'Release'
on:
    workflow_dispatch:
    workflow_run:
        workflows: ['Tests']
        types:
            - completed

jobs:
    release:
        name: 'Release'
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
            - name: 'Run semantic-release'
              run: |
                  yarn global add semantic-release@17 @semantic-release/exec
                  semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
